services:
  tailscale-ai:
    image: tailscale/tailscale:latest
    hostname: tailscale_ai
    environment:
      - TS_AUTHKEY=$SECRET_TS_AUTHKEY
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - ${PWD}/tailscale-nginx/state:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: unless-stopped
  certbot:
    image: certbot/dns-cloudflare
    volumes:
      - certbot_data:/etc/letsencrypt
      - ./cloudflare.ini:/root/cloudflare.ini:ro
    command: >-
      certonly --dns-cloudflare
      --dns-cloudflare-credentials /root/cloudflare.ini
      --dns-cloudflare-propagation-seconds 20
      --email $CERTBOT_EMAIL
      --agree-tos --no-eff-email
      --force-renewal
      -d $SERVICE_DOMAIN
      -d $WEB_DOMAIN
  nginx:
    image: nginx:latest
    volumes:
      - ${PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${PWD}/nginx/templates/:/etc/nginx/templates/:ro
      - ${PWD}/logs/:/var/log/nginx/
      - certbot_data:/etc/letsencrypt/
    restart: unless-stopped
    environment:
     - SERVICE_DOMAIN=$SERVICE_DOMAIN
     - WEB_DOMAIN=$WEB_DOMAIN
    depends_on:
      - certbot
      - tailscale-ai
    network_mode: service:tailscale-ai
  llm-provider:
    volumes:
      - /opt/ollama/ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    restart: unless-stopped
    image: ollama/ollama:rocm
    devices:
      - /dev/kfd
      - /dev/dri
  web-ui:
    container_name: web-ui
    image: ghcr.io/open-webui/open-webui:main
    restart: unless-stopped
    environment:
      OLLAMA_BASE_URL: http://llm-provider:11434
    volumes:
      - /opt/open_web_ui/:/app/backend/data


volumes:
  certbot_data: